In [ ]:
## Exercise 1: NumPy: Create an array with values ranging from 50 to 100

In [7]:
import numpy as np
import time
import sys

In [17]:
np.arange(50,101)

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
#Exercise 2: Add a border around an existing array
Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [24]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [39]:
a = np.ones((3,3))

In [40]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [41]:
np.pad(a, pad_width = 1)

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [42]:
## Exercise 3: Convert a list and tuple into arrays

In [44]:
# List# to array: 
#[1 2 3 4 5 6 7 8]
#Tuple to array: 
#[[8 4 6]
 #[1 2 3]]

In [45]:
A = [1, 2, 3, 4, 5, 6, 7, 8]

In [46]:
np.array(A)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [50]:
arr1 = np.array(A)

In [51]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [55]:
arr1 = arr1.reshape(2,4)

In [56]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [57]:
b = (8,4,6,1,2,3)
arr2 = np.array(b)

In [58]:
arr2

array([8, 4, 6, 1, 2, 3])

In [63]:
arr2.reshape(2,3)

array([[8, 4, 6],
       [1, 2, 3]])

## Exercise 4:  Convert the values of Centigrade degrees into Fahrenheit degrees
Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]

In [64]:
fvalues = [0, 12, 45.21, 34, 99.91]

In [65]:
f = np.array(fvalues)

In [66]:
f

array([ 0.  , 12.  , 45.21, 34.  , 99.91])

In [70]:
print(5*f/9 - 5*32/9)

[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


# Exercise 5: Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. 


Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24

In [90]:
y = np.array([1,2,3], dtype= np.float64)


In [91]:
y

array([1., 2., 3.])

In [92]:
print("size of the array:  ", y.size)
print("length of one array element in bytes: ", y.itemsize)
print("total bytes consumed by the elements of the array: ", y.nbytes)

size of the array:   3
length of one array element in bytes:  8
total bytes consumed by the elements of the array:  24


In [ ]:
## Exercise 6: Get the unique elements of an array

Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
 [2 3]]
Unique elements of the above array:
[1 2 3]




In [95]:
z= np.array([10, 10, 20, 20, 30, 30])

In [96]:
z

array([10, 10, 20, 20, 30, 30])

In [100]:
def unique(list1):
    unique_list = []
    for x in list1:
        if x not in unique_list:
            unique_list.append(x)
    for x in unique_list:
        print (x)

In [101]:
unique(z)

10
20
30


In [105]:
c = np.array([1, 1, 2, 3])

In [106]:
c.reshape(2,2)

array([[1, 1],
       [2, 3]])

In [107]:
unique(c)

1
2
3


## Exercise 7: Change the dimension of an array

Original array: [1 2 3 4 5 6 7 8 9]
Change array shape to (3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [119]:
arr1= np.arange(1,10)

In [120]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
arr1.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [122]:
## Exercise 8: Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive




In [141]:
x = np.linspace(2.5,6.5,30)

In [142]:
x

array([2.5       , 2.63793103, 2.77586207, 2.9137931 , 3.05172414,
       3.18965517, 3.32758621, 3.46551724, 3.60344828, 3.74137931,
       3.87931034, 4.01724138, 4.15517241, 4.29310345, 4.43103448,
       4.56896552, 4.70689655, 4.84482759, 4.98275862, 5.12068966,
       5.25862069, 5.39655172, 5.53448276, 5.67241379, 5.81034483,
       5.94827586, 6.0862069 , 6.22413793, 6.36206897, 6.5       ])

# Exercise 9: Convert 1-D arrays as columns into a 2-D array
Array1: [10 20 30]
Array2: [40 50 60]
Converted array
[[10 40]
 [20 50]
 [30 60]]


In [146]:
arr1 = np.array([10, 20, 30])
arr2 = np.array([40, 50, 60])

In [147]:
arr1

array([10, 20, 30])

In [148]:
arr2

array([40, 50, 60])

In [169]:
c = np.stack((arr1, arr2), axis =1)

In [170]:
c

array([[10, 40],
       [20, 50],
       [30, 60]])

# Exercise 10: Create a 5x5 matrix with row values ranging from 0 to 4
Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]

In [184]:
a = np.zeros((5,5))

In [185]:
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [186]:
b = np.arange(5)

In [187]:
b

array([0, 1, 2, 3, 4])

In [189]:
a+b

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

# Exercise 11: Sum of all the multiples of 3 or 5 below 100
[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318

In [196]:
x = np.arange(1,100)

In [197]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [222]:
n= x[(x % 3 == 0) | (x % 5 == 0)]
print(n[:1000])
# print sum the numbers
print(n.sum())

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


In [ ]:
## Exercise 12: Combine a one and a two dimensional array together and display their elements
##### Hint : np.nditer()

x = np.arange(4)
y = np.arange(4)
for a, b in np.nditer([x,y]):
    print(a)
    print(b)

In [223]:
t = np.arange(4)
t2= np.arange(4)
for t, t2 in np.nditer([t,t2]):
    print(t)
    print(t2)

0
0
1
1
2
2
3
3


In [228]:
t

array([0, 1, 2, 3])

In [229]:
t2

array(3)

In [226]:
t = np.arange(4)

In [227]:
t

array([0, 1, 2, 3])

In [239]:
t = np.arange(4)
t2= np.arange(4)

In [241]:
t

array(3)

In [242]:
t2

array(3)

In [240]:
for t, t2 in np.nditer([t,t2]):
    print(t)
    print(t2)

0
0
1
1
2
2
3
3


## Exercise 14: Add a new row to an empty numpy array

Empty array:
[]


After adding two new arrays:
[[10 20 30]
 [40 50 60]]

In [257]:
arr = np.empty((0,3), int)

In [258]:
arr

array([], shape=(0, 3), dtype=int32)

In [260]:
arr = np.append(arr, np.array([[10,20,30]]), axis=0)

In [261]:
arr

array([[10, 20, 30]])

In [264]:
arr = np.append(arr, np.array([[40,50,60]]), axis = 0)

In [265]:
arr

array([[10, 20, 30],
       [40, 50, 60]])

# Exercise 15: Write a NumPy program to join a sequence of arrays along a new axis. 

Original arrays:
[1 2 3]
[2 3 4]
Sequence of arrays along a new axis:
[[1 2 3]
 [2 3 4]]

Original arrays:
[[1]
 [2]
 [3]]

[[2]
 [3]
 [4]]
Sequence of arrays along a new axis:
[[1]
 [2]
 [3]
 [2]
 [3]
 [4]]


In [269]:
x

array([1, 2, 3])

In [270]:
y

array([2, 3, 4])

In [271]:
np.stack(x)

array([1, 2, 3])

In [272]:
np.stack(y)

array([2, 3, 4])

In [273]:
print(x,y)

[1 2 3] [2 3 4]


In [277]:
print(np.stack((x,y)))

[[1 2 3]
 [2 3 4]]


In [278]:
arr1= np.array([[1], [2], [3]])

In [279]:
arr1

array([[1],
       [2],
       [3]])

In [281]:
arr2= np.array([[2], [3], [4]])

In [283]:
arr2

array([[2],
       [3],
       [4]])

In [289]:
print(np.vstack((arr1, arr2)))

[[1]
 [2]
 [3]
 [2]
 [3]
 [4]]


# Exercise 13: Write a NumPy program to replace all elements of NumPy array that are greater than specified array.

Original array:
[[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than .5
[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]

In [294]:
x = np.array([[0.42436315, 0.48558583, 0.32924763],[0.7439979,  0.58220701, 0.38213418],[0.5097581,  0.34528799, 0.1563123]])

In [295]:
x

array([[0.42436315, 0.48558583, 0.32924763],
       [0.7439979 , 0.58220701, 0.38213418],
       [0.5097581 , 0.34528799, 0.1563123 ]])

In [296]:
x[x> .5] = .5

In [297]:
x

array([[0.42436315, 0.48558583, 0.32924763],
       [0.5       , 0.5       , 0.38213418],
       [0.5       , 0.34528799, 0.1563123 ]])